### ISSUE TITLE
Web FYKOSu - správa rozšíření

### ISSUE THREAD

**Issue by Werkov** [fykosak/dokuwiki-plugin-fkspoll#1]
From: @syselkk 

> Díval jsem se na to, jaký rozšíření máme vlastně na webu - a našel jsem tam
> chybovou hlášku:
> 
> getInfo() not implemented in admin_plugin_fkspoll and
> /network/data/www/fykos/fykos.cz-dokuwiki/lib/plugins//fkspoll/plugin.info.txt
> not found.
> Verify you're running the latest version of the plugin. If the problem
> persists, send a bug report to the author of the fkspoll plugin.

**Comment by cevro** [comment]
v commite 0e295ab6c0c5512c60417f6b22c80801bd21b9b4 bol pridaný plugin.info.txt a je správne vyplnený. Plugin na webe je v strej verzíi, zakázal som ho a tým hláška zmizla.
